[package]
name = "rustracer"
version = "0.1.0"
authors = ["Antoine BÃ¼sch <antoine.busch@gmail.com>"]

[[bin]]
name = "main"
path = "src/main.rs"
doc = false

[features]
default = ["minifb", "openexr"]

[dependencies]
approx = "0.1"
bitflags = "1"
chrono = "0.4"
clap = "2"
combine = "2"
crossbeam = "0.3"
error-chain = "0.11"
# ieee754 = "0.2"
ieee754 = { git = "https://github.com/abusch/ieee754.git" }
image = "0.16"
itertools = "0.6"
light_arena = "0.1"
minifb = { version = "0.10", optional = true }
num = "0.1"
num_cpus = "1"
openexr = { version = "0.5", optional = true }
pbr = "1.0.0"
# rustc-serialize = "0.3"
slog = { version = "2", features = ["max_level_debug", "release_max_level_debug"] }
slog-scope = "4"
slog-term = "2"
thread-id = "3"
tobj = "0.1"
uuid = { version = "0.5", features = ["v4"] }

[dev-dependencies]
rand = "0.3"

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = false
